name: LOCAL
variables:
  - name: baseUrl
    value: http://localhost:4000/api/v1
  - name: username
    value: johndoe
  - name: email
    value: admin.user@opero.local
  - name: password
    value: '12345678'
  - name: firstName
    value: John
  - name: lastName
    value: Doe
  - name: accessToken
    value:
  - name: companyId
    value: ae377aca-0388-44ae-9ad2-3af74f146961
  - name: departmentId
    value: dept-uuid-1
  - name: customerId
    value:
